[project]
name = "scholenopdekaart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "altair>=6.0.0",
    "duckdb>=1.4.4",
    "marimo[sql]>=0.19.7",
    "numpy>=2.4.1",
]
